### ISSUE TITLE
[cloud::microsoft::office365::management::plugin] Malformed JSON string reply

### ISSUE THREAD

**Issue by sikado** [centreon/centreon-plugins#1521]
Hello,

When trying to launch the following check, I get a JSON error. I'm suspecting an authorisation configuration mistake on my end but I guess the plugin should not "crash" in this case.
The other checks implemented in the plugin pack are working properly.

Command:
```
/usr/lib/centreon/plugins/centreon_office365_management_api.pl 
--plugin=cloud::microsoft::office365::management::plugin --mode=service-status 
--custommode='managementapi' --tenant='***' --client-id='***' --client-secret='***' 
--filter-service-name='' --filter-feature-name='' --warning-status='' 
--critical-status="" --debug
```

Reply:
```
UNKNOWN: Cannot decode json response: malformed JSON string, neither tag, array, object, 
number, string or atom, at character offset 0 (before "System.Collections.G...") at /usr/lib/centreon
/plugins/centreon_office365_management_api.pl line 6390.
======> request send
GET https://manage.office.com/api/v1.0/******/ServiceComms/CurrentStatus
Accept: application/json
Authorization: Bearer ****
User-Agent: centreon::plugins::backend::http::useragent

======> response done
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache
Date: Thu, 23 May 2019 14:39:32 GMT
Pragma: no-cache
Server: Microsoft-IIS/10.0
Server: Microsoft-IIS/10.0
Content-Length: 2452
Content-Type: text/plain; charset=utf-8
Expires: -1
Client-Date: Thu, 23 May 2019 14:39:33 GMT
Client-Peer: 52.109.76.109:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/ST=Washington/L=Redmond/O=Microsoft Corporation/OU=Microsoft IT/CN=Microsoft IT TLS CA 2
Client-SSL-Cert-Subject: /C=US/ST=WA/L=Redmond/O=Microsoft Corporation/OU=Microsoft Corporation/CN=manage.office.com
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
X-Activity-Id:
X-AspNet-Version: 4.0.30319
X-Instance-Name: Office365ServiceCommsWebService_Office365ServiceCommsWebService_IN_9
X-Powered-By: ASP.NET
X-Powered-By: ASP.NET
X-Time-Taken:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Office365ServiceComms.Common.OAuthAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Office365ServiceComms.MessageHandlers.RequestResponseLogHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Office365ServiceComms.Common.OAuthAuthorizeAttribute.OnAuthorization(HttpActionContext actionContext)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Office365ServiceComms.MessageHandlers.RequestResponseLogHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
```

And the app has the following rights on Office365:
 * Reports.Read.All 
 * User.Read
 * ServiceHealth.Read 

Thank you :)

**Comment by cgagnaire** [comment]
Hi @sikado,
This particular mode uses the Management API, the others use the Graph API.
Make sure to follow this link (https://docs.microsoft.com/en-us/office/office-365-management-api/get-started-with-office-365-management-apis#specify-the-permissions-your-app-requires-to-access-the-office-365-management-apis) to provide the correct rights.
The error here is clear : System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
Thank you!

**Comment by sikado** [comment]
Hi @cgagnaire,

Thanks for your feedback, indeed after adding "ActivityFeed.Read" in the Office365 Management API it's working perfectly.

Thanks a lot 😀

**Comment by cgagnaire** [comment]
Perfect! Thanks!
